# Generated by Django 3.2.4 on 2021-12-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211215_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/accounts/'),
        ),
    ]
