# Generated by Django 4.0.6 on 2022-07-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_newuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='image',
        ),
    ]
