# Generated by Django 4.0.6 on 2022-07-20 17:31

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_leader_uuid_alter_leader_parent_relation_numbre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='id',
        ),
        migrations.AlterField(
            model_name='leader',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
