# Generated by Django 4.0.6 on 2022-09-21 19:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_leader_id_alter_leader_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='bonus_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='bonus_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bonus_from', to='app.leader'),
        ),
        migrations.AddField(
            model_name='leader',
            name='bonus_type',
            field=models.CharField(blank=True, choices=[('parent', 'PARENT'), ('other', 'OTHER'), ('company', 'COMPANY')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
